### ISSUE TITLE
Flutter isolate spawning correctly but still blocking main thread

### ISSUE THREAD

**Issue by elian1203** [krista-koivisto/isolate_handler#1]
Hi. I am attempting to spawn a flutter isolate and run some code that involves opening a url and parsing some data. Using your package I am able to successfully  spawn the isolate using your example and run platform channel code, however this code still blocks the main thread. I am not sure if I'm doing something wrong with spawning or what the issue is, however it clearly blocks the loading of the UI and when I build the release apk the app just completely stops rather than being just slow.

Here is my test app.
https://pastebin.com/TkNcBiuv

**Comment by raccoons-are-goofy** [comment]
Apparently the reason for this is that the UI is run on the same thread as the platform thread in Flutter. The solution is to spawn a thread on the native side and perform the task in it.

More information available here:
https://github.com/flutter/flutter/issues/13937#issuecomment-529763378
