### ISSUE TITLE
Often On start have this issue : Unhandled Exception: 'package:isolate_handler/isolate_handler.dart': Failed assertion: line 192 pos 14: 'isolates.containsKey(to)': is not true.

### ISSUE THREAD

**Issue by abaturyna** [krista-koivisto/isolate_handler#14]
VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:isolate_handler/isolate_handler.dart': Failed assertion: line 192 pos 14: 'isolates.containsKey(to)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      IsolateHandler.send (package:isolate_handler/isolate_handler.dart:192:14)
#3      ParseResultScreenState.initState.<anonymous closure> (package:cosmeticscanner/pages/ParseResultScreen.dart:42:46)
#4      HandledIsolateMessenger.connectTo (package:isolate_handler/src/handled_isolate_messenger.dart:55:31)
#5      HandledIsolateMessenger._listenResponse (package:isolate_handler/src/handled_isolate_messenger.dart:75:7)
#6      HandledIsolateMessenger.listen.<anonymous closure> (package:isolate_handler/src/handled_isolate_messenger.dart:89:168)
#7      _rootRunUnary (dart:async/zone.dart:1206:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _CustomZ<…>

**Comment by deakjahn** [comment]
It's unfathomable, I regularly get GitHub notifications of other projects but not this one, so it slipped my attention, sorry. Could this be the same issue as mentioned here: https://github.com/deakjahn/isolate_handler/issues/16?

**Comment by deakjahn** [comment]
On second thought, no. This sounds more like you don't use the same name when starting the isolate and when sending a message to it.
