### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.

### ISSUE THREAD

**Issue by ghost** [krista-koivisto/isolate_handler#17]

**Comment by deakjahn** [comment]
Tell me a little bit more, please. There is no reference to any `toRawHandle` in the plugin, so this might come from some deeper parts, either in connection with using the plugin or not but you can't expect me to find out. :-))

**Comment by ghost** [comment]
BTW: I got the warning that IsolateHandler is deprecated.
I used the library as shown in the provided example and let it run in flutter debug mode, this exception was called, hence I tried the same without your library and no error was thrown. Can't tell more since I didn't test it out further, sorry.

**Comment by deakjahn** [comment]
> BTW: I got the warning that IsolateHandler is deprecated.

Where, how? No idea what this is all about...

**Comment by deakjahn** [comment]
Oh, you probably mean the older embedding. That doesn't mean a thing about the functionality of the plugin but I'll look into it.
