### ISSUE TITLE
FlutterIsolatePlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by abaturyna** [krista-koivisto/isolate_handler#19]
Xcode's output:
↳
    In file included from /Users/nastya/Dropbox/BUSINESS/Soft/flutter 1.2.13/.pub-cache/hosted/pub.dartlang.org/flutter_isolate-1.0.0+14/ios/Classes/FlutterIsolatePlugin.m:1:
    /Users/nastya/Dropbox/BUSINESS/Soft/flutter 1.2.13/.pub-cache/hosted/pub.dartlang.org/flutter_isolate-1.0.0+14/ios/Classes/FlutterIsolatePlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

My flutter doctor is : 

nastya@MacBook-Pro-Nastya ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale ru-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] Connected device (1 available)

• No issues found!
nastya@MacBook-Pro-Nastya ios %

**Comment by deakjahn** [comment]
`Flutter_isolate` is a dependency of this plugin, so if you have an error in its code, it might be better to file an issue there. :-)
