### ISSUE TITLE
How would one implement a timer based loop with this plugin?

### ISSUE THREAD

**Issue by 3SCadmin** [krista-koivisto/isolate_handler#26]
Hi,

There are very few examples on the web which use this plugin.
In my use-case I am trying to move an endless loop that uses the camera for motion-detection into an isolate.

So ideally I'd like to create a timer based loop inside the isolate
I kind-of got it to work (testing with the camera flash), but this feels like a hack:

`    messenger.listen((msg) async {`
 `   messenger.send('received command: ' + msg);`

    if (msg == 'stop') {
      run = false;
    }

    if (msg == 'start') {
      run = true;
    }

    while (run) {
      await Future<void>.delayed(Duration(seconds: 1));
      toggleFlash();
    }

     TorchLight.disableTorch(); //make sure that the light is off in the end
 ` });`

The reason I don't trust this approach is.... while trying different things I once forgot the "await" in the above code snippet.
The app tried to turn the flash on/off as fast as it could, and this resulted in the following warning in the debug console:
`I/Choreographer(13526): Skipped 116 frames!  The application may be doing too much work on its main thread.
`

Why did the main thread get blocked by something going wrong in the isolate?
Could you advise how we are intended to create timer based loops  with this plugin?

**Comment by deakjahn** [comment]
I don't really think this is anything to do with this plugin in special. :-))

You have several ways to create a periodic timer in Flutter and none of them is about awaiting repeatedly for every second. The most obvious choice would be `Timer.periodic()` where you provide a callback that does just what you want it to do. You will probably also want to store the timer object itself and then you can call its `cancel()` when you want to stop it.

**Comment by 3SCadmin** [comment]
> most obvious choice would be Timer.periodic()

Of course you are 100% correct.

I did try that first and erroneously concluded: "..didn't work"
I was extending your included example... which **has one line that ends the isolate after the first run**
I wasn't clever enough to connect those dots.

So now I have timer.periodic() sitting above messenger.listen()  and it all appears to work as expected.

**Comment by deakjahn** [comment]
Then we're happy. :-)

Actually, don't look for specific examples regarding this plugin on the net because there's nothing really specific. Look for examples about isolates in general. This plugin only really makes handling the isolates easier but they're not any different from any other isolates.
