### ISSUE TITLE
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by FLEasy** [krista-koivisto/isolate_handler#28]
Appears when calling sqlite in async thread after using isolate_handler
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
please help me to answer me thanks！

**Comment by FLEasy** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] VS Code (version 1.66.0)
[✓] Connected device (2 available)
    ! Error: longlonglong is busy: Fetching debug symbols for longlonglong.
      Xcode will continue when longlonglong is finished. (code -10)

**Comment by deakjahn** [comment]
Judging by the error message, this isn't coming from `sqlite` but `path_provider`. I don't do macOS development myself but https://pub.dev/packages/path_provider seems to suggest that the App Documents folder is supported.

Could you check whether you can get the same folder from `path_provider` without using an isolate? Or to get other app folder both with and without an isolate? Maybe some code or a reproducible demo of how to trigger this error? I think you can safely ignore `sqlite` for the test and only check getting the actual folder first.

**Comment by FLEasy** [comment]
@deakjahn Yes, I tested and found that the plugin in path_provider cannot work in data isolation

**Comment by FLEasy** [comment]
@deakjahn I have changed to a different way to achieve my needs and don't plan to use isolate anymore

**Comment by deakjahn** [comment]
@FLEasy OK. I would have suggested reading the folder first in your main program and passing it to the isolate as predetermined data. Isolates are very efficient on mobile, both Android and iOS, but I have very little experience with their problems on the desktop. So, if you still find something that needs to be addressed, just write.
