### ISSUE TITLE
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized

### ISSUE THREAD

**Issue by deakjahn** [krista-koivisto/isolate_handler#3]
Are you aware of some latest changes in Flutter that could render you plugin unusable? I follow the example to the letter but I always get the usual long message _(ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized. If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized()` first.)._

When you start to use defaultBinaryMessenger in line 152 of handled_isolate.dart, it's null.

**Comment by raccoons-are-goofy** [comment]
I was not aware of this, thank you for letting me know, I will look into it!

**Comment by raccoons-are-goofy** [comment]
This should be fixed now.

I created a custom class with the `ServicesBinding` mixin to call `ensureInitialized()` on since `WidgetBinding` instances can't be run in an isolate due to lack of window, rendering and painting bindings.

Thanks again for bringing this bug to my attention.

**Comment by deakjahn** [comment]
Can this change be seen in the source here? I'd be itching to try it out.

**Comment by deakjahn** [comment]
OK, I see the comments. I'll try and report back,

**Comment by raccoons-are-goofy** [comment]
> Can this change be seen in the source here? I'd be itching to try it out.

Yes it can, I also updated the [pub.dev package](https://pub.dev/packages/isolate_handler/versions/0.1.2+formatfix#-readme-tab-). :) You can ensure you get it by using:
```
dependencies:
    isolate_handler: ^0.1.2+formatfix
```

in your pubspec.yaml file.

**Comment by deakjahn** [comment]
Very nice, the platform calls are coming through now loud and clear. Thanks.

I'll have another very small suggestion, I'll open another issue to keep things organized.
