### ISSUE TITLE
Loses track of isolates

### ISSUE THREAD

**Issue by frank06** [krista-koivisto/isolate_handler#30]
Isolates keep piling up when using hot restart as there's no way to get hold of and kill them.

![i2](https://user-images.githubusercontent.com/66403/170373356-fa84bd49-fd8b-4bcb-890a-2fe6355fdbc8.png)

It appears that the `isolates` variable of `IsolateHandler` gets reset for every hot restart. 

`FlutterIsolate.runningIsolates` returns the correct number but alas IDs for isolates while offering no way to referencing them (as opposed to `handler.isolates` which does return isolate instances). An alternative in `flutter_isolate` is using the `killAll` API but that also has an issue: https://github.com/rmawatson/flutter_isolate/issues/107

**Comment by deakjahn** [comment]
Is this really a serious issue? I mean, hot restart is clearly just a debugging convenience -- a pretty useful one, but still nothing more -- and has no influence on how an app behaves in real life. Apart from that, the app receives no notification that it was restarted, so I really don't think we could do anything about it.

**Comment by frank06** [comment]
Feel free to rate the severity of the issue and your priority of fixing it however you like, I respect that. For me it is important because having a bunch of isolates logging to the console was confusing.

The app gets no notification that it was restarted but since it is starting again we can place that logic at app boot.

For those interested, my workaround is something like this:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _killIsolates();
  // ...
}

Future<void> _killIsolates() async {
  // ignore: unawaited_futures
  FlutterIsolate.killAll();
  await Future.delayed(Duration(milliseconds: 100); // not sure what the sweet spot is
}
```

**Comment by deakjahn** [comment]
I'm all ears to any suggestions, just that I can't yet see what we could do inside the plugin...
