### ISSUE TITLE
No errors in the console log

### ISSUE THREAD

**Issue by FreeStyle212** [krista-koivisto/isolate_handler#36]
When there are errors in my isolate they are not reported in the log. It simply crashes silently without any indication of why or what the problem was. If I am able to find the approximate area for the error I can use try catch to find more details. But is there any way for me to view errors within isolates the same as errors in the main isolate?

**Comment by deakjahn** [comment]
The plugin only calls your isolates, what they do and how they report is not its responsibility.

**Comment by FreeStyle212** [comment]
Thanks for replying. Do you know anything about this problem, do isolates not display errors in the console generally?

**Comment by deakjahn** [comment]
Mine normally do it all right. Do you write it directly or you use a logging package of some sorts?

**Comment by FreeStyle212** [comment]
I'm an idiot. I am running my isolate outside of the app, hence it has no stack trace. But this is nothing to do with the isolate even, simply the fact that the code is outside of runApp(). My solution is the stack_trace package, problem solved. Thanks for taking the time to reply to me, appreciated.

**Comment by deakjahn** [comment]
You're welcome. :-)
