### ISSUE TITLE
: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)

### ISSUE THREAD

**Issue by wajahat414** [krista-koivisto/isolate_handler#39]
Why cant we send a regular object as  a message to isolate?

**Comment by deakjahn** [comment]
Because `SendPort` doesn't support it: https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html

**Comment by wajahat414** [comment]
but how to send initial argument to function? bcoz regular isolates do support to pass initial argument to function,

**Comment by wajahat414** [comment]
like in entry point function i am not sure we are allowed pass any argument other than context

**Comment by deakjahn** [comment]
I'm not sure I can follow you here but you can send anything that you can serialize, for instance, to a JSON.
