### ISSUE TITLE
Suppress null error in dispose

### ISSUE THREAD

**Issue by deakjahn** [krista-koivisto/isolate_handler#4]
The dispose() at the end of isolate_handler.dart could use a question mark:

    isolates[name]?.dispose();

I know it's not nice to call it with a non-existent name but things happen sometimes, for instance when we have cleanup routines in different places and one already killed the isolate when the second one also gets called. Calling it can be placed inside a try-catch, sure, but... Just a little bit of fault tolerance.

Thanks for the very useful plugin.

**Comment by raccoons-are-goofy** [comment]
Yes, absolutely. This is a good thing to add, thank you for the suggestion.

**Comment by raccoons-are-goofy** [comment]
Done and published. :+1:
