### ISSUE TITLE
Sudden failure to compile

### ISSUE THREAD

**Issue by deakjahn** [krista-koivisto/isolate_handler#5]
Honest, officer, it was compiling half an hour ago. The Flutter Doctor doesn't say it was upgraded right now, the last one was five days ago. Any ideas? :-)

../../flutter-beta/.pub-cache/hosted/pub.dartlang.org/isolate_handler-0.1.2+hotfix1/lib/src/handled_isolate_binding.dart
:7:7: Error: The non-abstract class 'IsolateServicesBinding' is missing implementations for these members:
[   +1 ms]  - SchedulerBinding.addPersistentFrameCallback
[        ]  - SchedulerBinding.addPostFrameCallback
[        ]  - SchedulerBinding.addTimingsCallback
[        ]  - SchedulerBinding.cancelFrameCallbackWithId
[        ]  - SchedulerBinding.currentFrameTimeStamp
[        ]  - SchedulerBinding.currentSystemFrameTimeStamp
[        ]  - SchedulerBinding.debugAssertNoTransientCallbacks
[        ]  - SchedulerBinding.endOfFrame
[        ]  - SchedulerBinding.ensureFrameCallbacksRegistered
[   +2 ms]  - SchedulerBinding.ensureVisualUpdate
[   +1 ms]  - SchedulerBinding.framesEnabled
[        ]  - SchedulerBinding.handleAppLifecycleStateChanged
[   +1 ms]  - SchedulerBinding.handleBeginFrame
[        ]  - SchedulerBinding.handleDrawFrame
[        ]  - SchedulerBinding.handleEventLoopCallback
[        ]  - SchedulerBinding.hasScheduledFrame
[        ]  - SchedulerBinding.lifecycleState
[        ]  - SchedulerBinding.removeTimingsCallback
[   +2 ms]  - SchedulerBinding.resetEpoch
[        ]  - SchedulerBinding.scheduleForcedFrame
[   +1 ms]  - SchedulerBinding.scheduleFrame
[        ]  - SchedulerBinding.scheduleFrameCallback
[        ]  - SchedulerBinding.scheduleTask
[        ]  - SchedulerBinding.scheduleWarmUpFrame
[        ]  - SchedulerBinding.schedulerPhase

**Comment by deakjahn** [comment]
I did delete the plugin and let Flutter download it again.

**Comment by deakjahn** [comment]
```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (5 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = e:\Android\chrome.bat

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

**Comment by raccoons-are-goofy** [comment]
Thanks for the heads up once again, @deakjahn!

Looks like `SchedulerBinding` was added to Flutter's `ServicesBinding` mixin. Isolate Handler extends the `BindingBase` class with that mixin, which in turn now requires the additional dependency.

I uploaded the changes to GitHub now. I will push to pub.dev a bit later, but if you want the changes right away you can depend on the repository. :)

**Comment by deakjahn** [comment]
But how did this happen behind our backs? I swear I didn't upgrade Flutter today. :-)

No rush, I'm adding Flutter Web support to my app now and I haven't reached anything remotely similar to isolates yet (that won't work on Flutter Web, anyway). So, I just commented out that part for now.

Thanks.

**Comment by raccoons-are-goofy** [comment]
Not entirely sure why it only started complaining now. It should have done so as soon as you upgraded.

Either way, thanks for letting me know about the issue. :100:

**Comment by raccoons-are-goofy** [comment]
Upon further testing, the uploaded hotfix is insufficient to deal with the changes as `SchedulerBinding` requires UI components to be loaded.

This is a pretty big breaking change on the Flutter side and any additional fixes would just require relying even more on Flutter code not to change in the future. So due to lack of time to support this plugin, I will archive it.

If someone wants to take it over, they are more than welcome to do so.

**Comment by deakjahn** [comment]
It broke my app, too. Shouldn't you (and I second it) complain because of the breaking change?

**Comment by deakjahn** [comment]
You probably identified the commit that broke it, didn't you?

**Comment by raccoons-are-goofy** [comment]
I suspect there is little use in me complaining about it. In order to implement my previous fix I had to extend what is essentially an internal Flutter class, not one that is typically used by the end user. I wrongfully assumed it would be kept separate from the UI for the foreseeable future. The fault is on my end for making that assumption.

At the moment, there is very little that can be done that is not a hack or some other high cost fix, I'm afraid. :(

**Comment by deakjahn** [comment]
Bother. I actually only use it for one single purpose: crypto is painfully slow if done in Dart, PointyCastle or whatever. Platform implementations use nice hardware support and are pretty good. All I do from the isolate is to channel to my platform plugin to do AES for me. I'm afraid that if I have to ping-pong the data between the isolate and the main program, this will cancel out any potential speed benefit for me...

**Comment by deakjahn** [comment]
Quick question. Do you think the handler itself, without the MethodChannel support, will survive in the long run? Because the additional benefit of being able to collect and kill them might make it worthwhile to move the relevant parts into my app, anyway.

I never really checked this out, there was no need. Now I'll start but you should know it off-hand. :-)

**Comment by raccoons-are-goofy** [comment]
I'm afraid I simply don't have time for that level of support for this package as my priorities have changed significantly since I made it.

It is also worth mentioning that there is no performance improvement by running native code in a separate Dart isolate. The reason for this is that native code runs on the main (UI) thread no matter what happens on the Dart side, so the native plugin has to start its own thread on the native side in order to see improvements either way.

The isolate collection could be made to survive, but I simply don't have the time available to me right now to remove the communication parts. You may, of course, fork it and make the changes yourself. :)

**Comment by deakjahn** [comment]
No, I probably won't fork it but simply put the relevant parts into my own app. :-) I started to see if it compiles and then if it runs.

I have an uploader that uploads several files (encrypted) to our cloud when the user finishes. By putting all uploaders into their own isolates has been working very nicely so far. It's not necessarily the speedup that's important (although it never hurts) but it really provides a very smooth interface, with all uploads living their own lives, progressing separately and in parallel, with progress indicators and messages all responsive and nice. The whole upload feels snappy and nice, even if their combined time is not that far from a linear upload in the end.

So I don't want to lose that, at least not on mobile because on the Web, well, threre will be another can of worms.

**Comment by raccoons-are-goofy** [comment]
That sounds like a pretty good use case. :)

I will see if I have time to remove the communication aspect of it at some point and leave the isolate collection intact as it does seem to be of some use on its own. That should remove the excessive overhead of inter-isolate communication.

**Comment by raccoons-are-goofy** [comment]
Support for calls to native has now been removed and the rest of the isolate communication aspect kept. Will this still work for your application?

**Comment by deakjahn** [comment]
Well, well, we are almost identical, I did a few more changes that `pedantic`called for. :-))

I don't yet know because I have to find alternatives for the channel calls I can't have now in order to be able to test. I will do so soon and report back. Thanks.

**Comment by deakjahn** [comment]
Yes, thanks, it will. I just included `encrypt` to see. It crashed my phone immediately to reboot. :-) Then I replaced it with a plain copy instead of encryption just to see and that goes well with the isolates. I will see what I can do with the encryption, I only need to pass a filename now, not the actual data, so that might be handled with the normal isolate messaging after all.

**Comment by deakjahn** [comment]
Just one more question, Lieutenant. Although I went forward with other tasks, this just bugs me. :-) This plugin claims to allow MethodChannel calls. By looking into the rather simple source, I can't see anything that makes it tick but I might have missed something (and I didn't yet have the time to test it with a full example). I do remember seeing it when I looked for the solution but after having found yours I didn't pursue it any futher:

https://pub.dev/packages/flutter_isolate

**Comment by raccoons-are-goofy** [comment]
Yes, that one should work. It was released around the same time and uses a different method. I originally made mine to follow the suggestions [posted in this comment](https://github.com/flutter/flutter/issues/13937#issuecomment-357197834).

From what I recall, flutter_isolate creates a whole new view/UI engine on the native side (which is basically what is lacking for native calls to work in isolates). It is certainly an option worth checking out. :)

**Comment by deakjahn** [comment]
Just a plain vanilla, empty platform view, no engine or anything that fancy. Is that really enough to make it work? I'm on friendly terms with platform views, I have created quite a few of them and using in some apps (like PDF or 3D model viewer).

Yes, I remember the topic, I just happened to add a few words to it.

Now you really got me going. I'll fork yours and see what happens if it's backed by that `future_isolate` kind of isolate. Expect a PR if it holds water. :-)

**Comment by raccoons-are-goofy** [comment]
I'm not entirely sure about the workings of flutter_isolate behind the scenes, just what I remember reading. :)

Good luck! The PR is certainly appreciated if you can interface the two.

**Comment by deakjahn** [comment]
Three files, one .dart and one each for each platform... If it works, it will work. :-)

**Comment by deakjahn** [comment]
By the way. The mobile platforms expect us to provide an ID in the usual Java reverse format, `com.something.isolate_handler`. Do you have a domain you normally use for such plugins? I really don't want to hijack it so it will be called what you want to call it.

**Comment by raccoons-are-goofy** [comment]
I don't really have one, but you could use `com.snarkypixel.isolate_handler`. :+1:

**Comment by deakjahn** [comment]
On the other hand, if we just depend on it, it might not be needed at all.

Well. It took some time to realize I was referencing the files I copied into my app, not the forked version I modified. Well...

```
It is possible the default GeneratedPluginRegistrant is attempting to register
E/FlutterIsolate(21460): a plugin that uses registrar.activity() or a similar method. Flutter Isolates have no
E/FlutterIsolate(21460): access to the activity() from the registrant. If the activity is being use to register
E/FlutterIsolate(21460): a method or event channel, have the plugin use registrar.context() instead. Alternatively
E/FlutterIsolate(21460): use a custom registrant for isolates, that only registers plugins that the isolate needs
E/FlutterIsolate(21460): to use.
```

So, this seems to be on the right track already. Yes, I'm likely to have such a plugin. So, it might work, just be picky about what plugins it likes.

**Comment by deakjahn** [comment]
OK. Changes committed to https://github.com/deakjahn/isolate_handler. Not yet PR'd to you. I only have a hunch that it will work but I can't actually test before I separate my plugin into two halves, one that requires the Android activity and one that doesn't.

**Comment by deakjahn** [comment]
Temporarily stuck at https://github.com/rmawatson/flutter_isolate/blob/master/lib/flutter_isolate.dart#L39 .

You did that brave thing of abstracting away the messaging and use the `HandledIsolateContext` as a message to return to the starting function, with the primary (or only) reason to make the user pass it back on to `HandledIsolate.initialize()`. That should be nice but the catch is that in that line above, FlutterIsolate sends the list of `[userEntryPointId, message]` over the port. And the result, unfortunately, is:

```
ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
_SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:219:70)
_SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:203:5)
FlutterIsolate.spawn.<anonymous closure> (package:flutter_isolate/flutter_isolate.dart:39:17)
```

Ports regularly get sent across so I wasn't sure why this caused any trouble here. (`userEntryPointId` is just a handle, an `int`). Then it dawned on me that being inside a class might be the reason. So, in the end, I finally killed `HandledIsolateContext` and only send the `SendPort`.

And it works now. PR sent.

**Comment by raccoons-are-goofy** [comment]
@deakjahn I am going to pull the plug on this package once again. I'm sorry it came to this, but my workload just increased further and I lack the time required to keep up with the required maintenance for this package. If you wish to take it over, I can transfer ownership to you.

**Comment by deakjahn** [comment]
Now that it works and provides a much needed solution, let's not kill it. :-) I'm all right with GitHub but never did anything on Pub yet. There is a first time for everything... So, tell me what I need to do.

**Comment by raccoons-are-goofy** [comment]
You will need to create a pub.dev account and I will add you as publisher. You can then remove me using the following and ownership will be fully yours:

`pub uploader remove krista@snarkypixel.com`

Let me know your email that you signed up with (it will be public on the package page, just FYI) and I will add you.

**Comment by deakjahn** [comment]
The address on my GitHub page (https://github.com/deakjahn?tab=repositories) will do just fine. Shall I fork the code or that will be done as well?

**Comment by raccoons-are-goofy** [comment]
Publisher invite sent. I will transfer ownership of this GitHub repository to you, so no need to fork it. :)

**Comment by deakjahn** [comment]
I'm stuck right now because I see no other way to register at Pub.dev but using a Google account...

**Comment by raccoons-are-goofy** [comment]
Yes, as I recall you have to have a Google account in order to use pub.dev. :confused: You can create a Google account using your already existing e-mail address if you don't already have one. If you prefer not having a Google account at all, I suspect there's little to be done.

**Comment by deakjahn** [comment]
I do have a G account, of course, even more than one, the only problem is that I don't want to advertise *that* account. I actually only use my G mail to power my phone and related stuff, not advertising it on purpose to avoid spam on that one (and I managed to avoid it until now). For all correspondence, I use addresses of my own domains. So, I think I'll have to create a new account now with this e-mail.

**Comment by deakjahn** [comment]
OK, then, sorry for the extra work. Changed the e-mail on the repository page to a new gmail one, please, send the invitation again to this one. (Actually, you can't set up an account with an existing address, that doesn't work any more, although it used to eons ago. Now you can only do it in a paid company account, letting G handle all of the domain).

**Comment by raccoons-are-goofy** [comment]
Oh, that's unfortunate. :/ Invitation sent.

**Comment by raccoons-are-goofy** [comment]
Sent a GitHub transfer request as well.

Thank you for taking over work on this package. I am glad it moved to such capable hands. :)

**Comment by deakjahn** [comment]
Thanks a lot, it's a pleasure. :-)

Then are we at the end source-wide, it just needs to be published under a new version number?

**Comment by raccoons-are-goofy** [comment]
That's right. :) Increase the version number and add an entry to the `CHANGELOG.md` file and you're good to publish. Oh, and you might want to update the `README.md` with the new changes.

**Comment by deakjahn** [comment]
All the more because it's a breaking change now. OK, I cloned it fresh again, first I see if it compiles, the example runs, change the log and then publish.

**Comment by deakjahn** [comment]
Well, I hope, mostly... :-)

I called it 0.3.0, changed the texts, published it. The only interesting thing I probably don't have a handle on yet is that if I change my .yaml to need ^0.3.0, it's downloaded automatically, but if I keep it ^0.2.whatever, it stays. Maybe intentional with versions and I should RTFM?

**Comment by raccoons-are-goofy** [comment]
~~That's interesting, it should work in the opposite way according to [TFM](https://dart.dev/tools/pub/dependencies#version-constraints).~~ (See edit.)

Looks good! :+1: The pub.dev [package health analysis](https://pub.dev/packages/isolate_handler#-analysis-tab-) still shows that the sources should be formatted and that it lacks acccess to the `README.md` file for some reason.

If you wondered why I had really ugly formatting in some places, it's because pub.dev wants you to run `flutter format` on everything in order to ensure that the package gets a perfect health score. :wink:

Edit: Oh, I misunderstood the explanation. What you're experiencing is the correct behavior for pubspec.yaml files.

**Comment by deakjahn** [comment]
You mean dartfmt? I use it all the time, it became second nature to me. I mostly agree with what it does and use extra comments to force it when it does something different.

The link is because I modified my `master` branch to match your `0.2.0` and I didn't change it in the path. I'll fix it.

**Comment by deakjahn** [comment]
Well, *dartfmt* said nothing to change. Strange,

**Comment by raccoons-are-goofy** [comment]
Unfortunately `dartfmt` and `flutter format` produce slightly different outputs. In my experience `flutter format` is more aggressive and enforces the 80 character line-limit with no exceptions among other things.

Edit to add: I always forgot to run it as you can tell from the amount of `formatfix` releases in the CHANGELOG, because I use `dartfmt` with my IDE.

**Comment by deakjahn** [comment]
Yes, I also compared the two and found the same. Will anybody ever check this score? I can't imagine it's that important. :-)

Needless to say, I hate and abhor that 80-char limit with the current 30-whatever-inch monitors we use today.

**Comment by raccoons-are-goofy** [comment]
I'm not sure about others, but I use it whenever I consider a package for professional applications to check how seriously the publisher takes code quality and adhering to standards.

I fully agree about the 80-char limit being unnecessary these days. I wish pub.dev accepted `dartfmt` packages too, as it's more reasonable.

**Comment by deakjahn** [comment]
I have to confess I never looked at those figures. Now in retrospect, I tought it was some kind of a popularity index or similar by users and I was never really interested what others think if I find a package useful. :-) There is a popularity inside, now I see.

But wait, the formatting doesn't count against maintenance, it's only a suggestion. So, let them fight, `format` and `dartfmt` to their hearts' contents. :-)

**Comment by raccoons-are-goofy** [comment]
Looks like you're right, it still gives you a 100 for health. :)

**Comment by deakjahn** [comment]
OK, then the path will be fixed in the next one.

I wish image manipulation in Flutter Web would be as simple as this...
